#!/usr/bin/env bash


<< 'multilinecomment'
    
    zoek?
    Dutch, weak verb, present tense
    to search, look for, to seek
    
    A basic script to search for native, flatpak and snap packages with one command
    run this script with the search string as argurment

    Currently only works with my personal favorite linux distros, Solus, Debian and Debian derivates.
    Testing Redhat, Fedora and CentOS support

    e.g.:
    zoek packagename
    
    screenshot
    https://i.imgur.com/Zy8mW0N.png
    
    instructions
    Save this file as /usr/bin/zoek
    Set execute permissions: chmod +x /usr/bin/zoek
    
multilinecomment



STRING1=$1

declare -A osInfo;
osInfo[/usr/bin/eopkg]=eopkg
osInfo[/usr/bin/apt-cache]=apt-cache
# osInfo[/usr/bin/yum]=redhat # testing

for f in ${!osInfo[@]}
do
    if [[ -f $f ]];then
        echo Package manager: ${osInfo[$f]} | lolcat

echo Searching for native packages... | lolcat
$f search $STRING1

echo .
echo looking for snap packages... | lolcat
snap search $STRING1

echo .
echo flatpak maybe? | lolcat
flatpak search $STRING1

    fi
done
